runs:
  - runtime: ollama
    model: "qwen2.5:0.5b"
  - runtime: foundry-local
    model: qwen2.5-0.5b
    device: npu
  - runtime: foundry-local
    model: qwen2.5-0.5b
    device: gpu
  - runtime: foundry-local
    model: qwen2.5-0.5b
    device: cpu
